#!/bin/sh
set -e

### BEGIN INIT INFO
# Provides:           custdocker
# Required-Start:     docker
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start:      2 3 4 5
# Default-Stop:       0 1 6
# Short-Description:  Creat Docker customization.
# Description:
#  Create docker customization.
### END INIT INFO

if [ -d /etc/docker ]; then
	if [ ! -f /etc/docker/daemon.json ]; then
		cp /custom/daemon.json /etc/docker/daemon.json
		systemctl restart docker
	fi
fi
