---
apiVersion: v1
kind: Service
metadata:
  name: kibana-cs
  labels:
    app: kibana-cs
spec:
  ports:
  - port: 5601
    targetPort: kibana-http
    protocol: TCP
    nodePort: 32752
  type: NodePort
  selector:
    app: kibana-ui
---
apiVersion: v1
kind: Pod
metadata:
  name: kibana-ui
  labels:
    app: kibana-ui
spec:
  containers:
  - name: kibana-ui
    image: 192.168.1.101:5000/plawson/kubernetes-kibana:5.6.4
    resources:
      limits:
        cpu: "0.5"
    env:
      - name: ELASTICSEARCH_URL
        value: http://elasticsearch:9200
      - name: XPACK_MONITORING_ENABLED
        value: "false"
      - name: XPACK_SECURITY_ENABLED
        value: "false"
      - name: XPACK_GRAPH_ENABLED
        value: "false"
      - name: XPACK_ML_ENABLED
        value: "false"
      - name: XPACK_REPORTING_ENABLED
        value: "false"
    ports:
    - name: kibana-http
      containerPort: 5601
      protocol: TCP
