---
apiVersion: v1
kind: Service
metadata:
  name: kafka-manager
  labels:
    name: kafka-manager
spec:
  ports:
  - port: 9000
    targetPort: kafka-mgr-http
    protocol: TCP
    nodePort: 32751
  type: NodePort
  selector:
    name: kafka-manager
---
apiVersion: v1
kind: Pod
metadata:
  name: kafka-manager
  labels:
    name: kafka-manager
spec:
  containers:
  - name: kafka-manager
    image: 192.168.1.101:5000/plawson/kubernetes-kafka-manager
    ports:
    - name: kafka-mgr-http
      containerPort: 9000
    resources:
      limits:
        cpu: "0.5"
    env:
    - name: ZK_HOSTS
      value: zk-cs.default.svc.cluster.local:2181
