apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-kafka
spec:
  capacity:
    storage: 900Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.101
    path: "/synology/nfs/kafka"
